### ISSUE TITLE
Create separate NuGet libs for each file provider type?

### ISSUE THREAD

**Issue by pauldotknopf** [dazinator/Dazinator.Extensions.FileProviders#32]
I needed the memory file provider for unit tests. I think it is weird I couldn't use it because of the ASP.NET references were outdated (considering I don't need them, see #31).

I'd send a pull request, but I'm on a Mac, and you are referencing net4*, which I can't guarantee works on this platform.

**Comment by dazinator** [comment]
Im open to splitting the providers into seperate projects, starting with the inmemory if that is what you mean? I am also open to retargerting to netstandard rather than full net framework. The lowest netstandard possible the better, ideally < 2. I dont have much time for this at the present but feel free to fork and make changes to anything holding you back, and I'd consider PR's

**Comment by pauldotknopf** [comment]
Great, I'll look into it. Thanks!

**Comment by dazinator** [comment]
Note to self, should also Rename to Dazinator.Extensions.FileProviders (i.e drop the "AspNet" portion of the name) from this repo name, and from the nuget package.
